/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gr.open.marketplace.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import gr.open.marketplace.model.AdminIPValidationData;
import gr.open.marketplace.service.AdminIPValidationDataLocalServiceUtil;

/**
 * The extended model base implementation for the AdminIPValidationData service. Represents a row in the &quot;opengr_AdminIPValidationData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdminIPValidationDataImpl}.
 * </p>
 *
 * @author cotria
 * @see AdminIPValidationDataImpl
 * @see gr.open.marketplace.model.AdminIPValidationData
 * @generated
 */
public abstract class AdminIPValidationDataBaseImpl
	extends AdminIPValidationDataModelImpl implements AdminIPValidationData {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a admin i p validation data model instance should use the {@link AdminIPValidationData} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			AdminIPValidationDataLocalServiceUtil.addAdminIPValidationData(this);
		}
		else {
			AdminIPValidationDataLocalServiceUtil.updateAdminIPValidationData(this);
		}
	}
}